import myImg from "../assets/myImg.jpg";

const Home = () => {
  return (
    <div
      className="
        bg-light
        min-h-screen
        flex
        flex-col
        justify-center
        items-center
      "
      id="home"
    >
      <div
        className="
          flex
          flex-col
          gap-4
          justify-start
          w-[80%]
          pt-8
          pb-[20%]
          lg:flex-row
          lg:gap-16
          lg:justify-center
          lg:pt-0
          lg:pb-20
        "
      >
        <div
          className="
            h-full
            flex
            flex-col
            justify-center
            lg:pt-24
            xl:pt-44
          "
        >
          <h2
            className="
              underline
              text-dark 
              font-medium 
              text-md
              md:mt-16
              lg:text-2xl
            "
          >
            HELLO
          </h2>
          <h1
            className="
              text-dark
              font-thin
              text-2xl
              mt-4
              lg:text-4xl
              lg:mt-8
            "
          >
            I'm
          </h1>
          <div
            className="
              text-primary
              font-bold
              text-7xl
              mt-2
              lg:text-8xl
              lg:mt-8
            "
          >
            <h1>ANN</h1>
            <h1>PHUNG</h1>
          </div>
          <p
            className="
              text-dark
              text-xs
              mt-2
              pt-2
              border-t-[1px]
              border-dark/10
              w-[fit-content]
              lg:text-base
            "
          >
            a web designer and developer
          </p>
        </div>
        <div
          className="
            xl:w-[500px]
          "
        >
          <img 
            className="
              w-[100%]
              bg-primary
              pl-2
              object-contain
              rounded-tr-full
              border-primary
              border-r-[20px]
              shadow-2xl
              shadow-primary
              mt-8
            "
            src={myImg} alt="my image" 
          />
        </div>
      </div>
    </div>
  );
};
export default Home;
